---
title: "Data Transformation"
author: "Raghu Kulkarni"
date: "10/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r basic}
library(tidyverse)
ggplot(data = mpg) + geom_point(mapping = aes(x=displ, y=hwy))
filter(mpg, cyl==8)
filter(diamonds, carat>3)
```

```{r arrange}
library(nycflights13)
library(tidyverse)
nycflights13::flights
#view(nycflights13::flights)

jan1 <- filter(flights, month==1, day==1)
filter(flights, month=1)

filter(flights, month == 11 | month == 12)
nov_dec <- filter(flights, month %in% c(11,12))

filter(flights, !(arr_delay > 120) | (dep_delay) > 120)
filter(flights, arr_delay <= 120 & dep_delay <= 120)

df <- tibble(x=c(1,NA,3))
filter(df, x>1)
filter(df, is.na(x) | x>1)

filter(flights, arr_delay >= 120)
filter(flights, dest == "IAH" | dest == "HOU")
filter(flights, carrier %in% c("UA","AA","DL"))
filter(flights, month %in% c(7,8,9))
filter(flights, arr_delay >= 120 & dep_delay == 0)
filter(flights, arr_delay >= 60 & sched_arr_time - arr_time >= 30)
filter(flights, between(dep_time, 0000, 0600))

filter(flights, is.na(dep_time))

```
```{r arrange}
arrange(flights, year, month, year)
arrange(flights, desc(dep_delay))

df <- tibble(x = c(5, 2, NA))
arrange(df, desc(is.na(x)) )

```
```{r select}
select(flights, year, month, day)
select(flights, year:day)
select(flights,-(year:day))
rename(flights, tail_num = tailnum)
select(flights, time_hour, air_time, everything())
select(flights, dep_time, dep_time)
vars <- c("year", "month", "day", "dep_delay", "arr_delay")
one_of(vars)
select(flights, contains("TIME"))

flights_sml <- select(flights, 
  year:day, 
  ends_with("delay"), 
  distance, 
  air_time
)
mutate(flights_sml, gain = dep_delay - arr_delay, speed = distance/air_time*60,
       hours = air_time / 60,
       gain_per_hour = gain / hours
       )
transmute(flights,
  dep_time,
  hour = dep_time %/% 100,
  minute = dep_time %% 100
)
filter(flights, min_rank(desc(dep_delay)<=10))
flights %>% top_n(n = 10, wt = dep_delay)

y <- c(1, 2, 3, NA, 4, 5)
min_rank(y)
ntile(row_number(y),3)
min_rank(desc(y))
row_number(y)
dense_rank(y)
summarise(flights, delay = mean(dep_delay, na.rm = TRUE))
by_day <- group_by(flights, year, month, day)
summarise(by_day, delay = mean(dep_delay, na.rm = TRUE))

```

```{r pipe}
by_dest <- group_by(flights, dest)
delay <- summarise(by_dest,
                  count = n(),
                  dist = mean(distance, na.rm = TRUE),
                  delay = mean (arr_delay, na.rm = TRUE)
                   )
delay <- filter(delay, count > 20, dest != "HNL")

ggplot(data = delay, mapping = aes(x = dist, y = delay)) +
  geom_point(aes(size = count), alpha = 1/3) +
  geom_smooth(se = FALSE)


delays <- flights %>% 
  group_by(dest) %>% 
  summarise(
    count = n(),
    dist = mean(distance, na.rm = TRUE),
    delay = mean(arr_delay, na.rm = TRUE)
  ) %>% 
  filter(count > 20, dest != "HNL")

flights %>% 
  group_by(year, month, day) %>% 
  summarise(mean = mean(dep_delay, na.rm = TRUE))

not_cancelled <- flights %>% 
  filter(!is.na(dep_delay), !is.na(arr_delay))

not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(mean = mean(dep_delay))

delays <- not_cancelled %>% 
  group_by(tailnum) %>% 
  summarise(
    delay = mean(arr_delay)
  )

ggplot(data = delays, mapping=aes(x=delay)) +
  geom_freqpoly(binwidth = 10)

delays <- not_cancelled %>% 
  group_by(tailnum) %>% 
  summarise(
    delay = mean(arr_delay, na.rm = TRUE),
    n = n()
  )

ggplot(data = delays, mapping = aes(x = n, y = delay)) + 
  geom_point(alpha = 1/10)

delays %>% 
  filter(n > 25) %>% 
  ggplot(mapping = aes(x = n, y = delay)) + 
    geom_point(alpha = 1/10)

batting <- as_tibble(Lahman::Batting)

batters <- batting %>% 
  group_by(playerID) %>% 
  summarise(
    ba = sum(H, na.rm = TRUE) / sum(AB, na.rm = TRUE),
    ab = sum(AB, na.rm = TRUE)
  )

batters %>% 
  filter(ab > 100) %>% 
  ggplot(mapping = aes(x = ab, y = ba)) +
    geom_point() + 
    geom_smooth(se = FALSE)

not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(
    first = min(dep_time),
    last = max(dep_time)
  )
not_cancelled %>% 
  group_by(year, month, day) %>% 
  mutate(r = min_rank(desc(dep_time))) %>% 
  filter(r %in% range(r))

not_cancelled %>% 
  group_by(dest) %>% 
  summarise(carriers = n_distinct(carrier)) %>% 
  arrange(desc(carriers))

not_cancelled %>% 
  count(tailnum, wt = distance)

not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(n_early = sum(dep_time < 500))

not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(hour_perc = mean(arr_delay > 60))

daily <- group_by(flights, year, month, day)
(per_day   <- summarise(daily, flights = n()))
(per_month <- summarise(per_day, flights = sum(flights)))

daily %>% 
  ungroup() %>%             # no longer grouped by date
  summarise(flights = n())
flights_sml %>% 
  group_by(year, month, day) %>% 
  filter(rank(desc(arr_delay))<10)

popular_dests <- flights %>% 
  group_by(dest) %>% 
  filter(n()>365)
popular_dests

popular_dests %>% 
  filter(arr_delay > 0) %>% 
  mutate(prop_delay = arr_delay/sum(arr_delay)) %>% 
  select(year:day, dest, arr_delay, prop_delay)

flights %>%
    ggplot(aes(x=factor(hour), fill=arr_delay>5 | is.na(arr_delay))) + geom_bar()
```












