dbt_modeling:
  outputs:
    serving:
      dbname: dev
      host: <REDSHIFT_ENDPOINT>
      password: Defaultuserpwrd1234+
      port: 5439
      schema: deftunes_serving
      threads: 1
      type: redshift
      user: defaultuser
  target: serving