services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_DEBUG: ${FLASK_DEBUG}
    env_file:
      - .env
  redis:
    image: "redis:alpine"