name: Github Secrets Scanning

on:
  workflow_dispatch: 
jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Step Checkout Source Repo
        uses: actions/checkout@v4
        with:
          repository: rdkworld/portfolio.git
          ref: main
          fetch-depth: 0
          
      - name: Step Secret Scan
        uses: trufflesecurity/trufflehog@main
        # with:
          # path: ./
          # base:
          # head:
          # extra_args: --only-verified
